stages:
  - deploy

.serverless:deploy:
  image: registry.gitlab.com/noknox/cicd/cicd-templates/serverless-python-deploy:3.7.3
  stage: deploy
  when: manual
  except:
    - external_pull_requests
  script: 
    - sls deploy --stage ${environment}
