stages:
  - deploy

.serverless:deploy:
  image: docker.pkg.github.com/noknox/cicd.templates/serverless-dotnet-deploy:2.1
  stage: deploy
  when: manual
  except:
    - external_pull_requests
  script:
    - sls deploy --stage ${environment}
