stages:
  - deploy

.serverless:deploy:
  image: registry.gitlab.com/noknox/cicd/cicd-templates/serverless-dotnet-deploy:2.1
  stage: deploy
  when: manual
  except:
    - external_pull_requests
  script:
    - sls deploy --stage ${environment}
